### ISSUE TITLE
Assign Dashboard Variable to Element in Initial Request

### ISSUE THREAD

**Issue by greasyfamilyzhi** [VolkovLabs/volkovlabs-form-panel#159]
How can we assign dashboard variable to an element in the initial request?

I have a dashboard variable $IconVar, tried below but it doesn't work

const formIcon= elements.find((element) => element.id === "icon");
formIcon.value = {$IconVar};

**Comment by greasyfamilyzhi** [comment]
Solved! Read the documentation again and use templateService:
formIcon.value = templateService.getVariables().find(({ name }) => name === "$IconVar").current.value;

**Comment by mikhail-vl** [comment]
@greasyfamilyzhi I just looked at the code, and we do replace variables in the Initial and Update requests.

```
    /**
     * Function
     */
    const f = new Function(
      'options',
      'data',
      'response',
      'elements',
      'locationService',
      'templateService',
      'onOptionsChange',
      'initialRequest',
      'setInitial',
      'json',
      'initial',
      'notifyError',
      'notifySuccess',
      replaceVariables(code)
    );
```

  We use `replaceVariables`, which supports scopedVars for repeat panels if you need it. What was the error when you tried?
  I think the value should be quoted because the string returned as is. It's would be better than using the `templateService`.

```
formIcon.value = "$IconVar";
```

  Let me know if it works. I need to update the documentation for it.

**Comment by mikhail-vl** [comment]
To update documentation: https://github.com/VolkovLabs/volkovlabs.io/issues/348
