### ISSUE TITLE
Import getDataSourceSrv from grafana/runtime

### ISSUE THREAD

**Issue by rzvcs** [VolkovLabs/volkovlabs-form-panel#163]
Hi!

Would it be possible to expose getDataSourceSrv for the form's custom code part? I would like to be able to control the datasource query() method, in the Update Request section of this panel.
Combining the Data Manipulation panel with Grafana's JSON API Datasource could avoid some CORS issues. That is, the Data Manipulation panel makes the requests from the browser and I would like to avoid that. The JSON API Datasource is executed by the backend directly, which is safer in my application.

**Comment by mikhail-vl** [comment]
@rzvcs Unfortunately, `getDataSourceSrv` can't be exposed due to security reasons. I just removed it from the Apache ECharts panel by recommendation from the Grafana Plugin team.

  I like how it's done in the https://github.com/speakyourcode/grafana-button-panel by selecting the Data Source from the panel options, and I wanted to do the same in the upcoming release. We are planning to release it next week.

  We have a blog post on how you can use NGINX or Custom Data source to avoid CORS issues if interested: https://volkovlabs.io/blog/how-to-connect-the-data-manipulation-plugin-for-grafana-to-api-server-1abe5f60c904/

**Comment by nicolaerosia** [comment]
@mikhail-vl do you have a list of interesting panels/plugins? Where do you find them?:)

**Comment by mikhail-vl** [comment]
@nicolaerosia We have dashboard with Grafana Catalog releases which I monitor: https://release.volkovlabs.io/d/hHK1qmpnk/grafana-catalog-updates?orgId=1

**Comment by rzvcs** [comment]
> @rzvcs Unfortunately, `getDataSourceSrv` can't be exposed due to security reasons. I just removed it from the Apache ECharts panel by recommendation from the Grafana Plugin team.

I see. I think I posted this issue at the same time you created the pull request for Echarts panel.

> I like how it's done in the https://github.com/speakyourcode/grafana-button-panel by selecting the Data Source from the panel options, and I wanted to do the same in the upcoming release. We are planning to release it next week.

It would be interesting to have this as an option. The view that I have is:
- have Data Manipulation as a control panel - fields, value conversions etc.
- at submit, it makes a request through the JSON API Data Source of this panel to a stateless API 
- have a second panel that uses the Data Manipulation panel as a Datasource (Dashboard Datasource type) 
- display the data (tabular, graphical etc.)
