### ISSUE TITLE
Add custom code to update values before the update request

### ISSUE THREAD

**Issue by vanimesh** [VolkovLabs/volkovlabs-form-panel#210]
Hi @zverbatim / @asimonok / @mikhail-vl / @githubDante / @maleksan (sorry for tagging you all didnt know whome to tag).  First of all thank you for the plugin which is continuoysly improving with features and works flawlessly. 

I have added two elements(example start and end date)of type date. It also works if start date is > end date. How can i implement it ? I want user to select proper dates and then only the button should be enabled.

Also when i am trying to send the values over API. The time is not properly inserted, it always have the difference of 5 hours. 

Also can the date time format can be changed  as per my wish ?

**Comment by vanimesh** [comment]
Hi @mikhail-vl , any update on my above ask ?

**Comment by mikhail-vl** [comment]
@vanimesh Regarding two elements, there was another requests to implement dependency of the elements. I am think how to implement it in the future releases, for now it's not supported.

  Date elements works with the browser time, but the request will be sent in UTC. So your API should expect UTC time, not the local user's time.

```
dateTime: "2023-07-26T19:22:55.000Z"
``` 

  You can update the data time format using Custom Update Request, instead of predefined, and update any values as you wish: https://volkovlabs.io/plugins/volkovlabs-form-panel/request/

  I will think of implementing the Custom Code for the updated request before the request, which can help with your request.

**Comment by vanimesh** [comment]
So can we send the browser timezone as a parameter? To our api? Also really waiting for dependency elements.

**Comment by mikhail-vl** [comment]
@vanimesh If you need the browser timezone, add it to the custom code for the initial request.

  You can have a hidden String element and update its value following documentation to the browser timezone: https://volkovlabs.io/plugins/volkovlabs-form-panel/code/

**Comment by mikhail-vl** [comment]
Dependency for elements will be implemented in the upcoming version https://github.com/VolkovLabs/volkovlabs-form-panel/issues/198

**Comment by mikhail-vl** [comment]
@vanimesh Please try to stick to one question per issue. I will keep this issue for adding additional custom code to execute before the update request.
