### ISSUE TITLE
Add language support

### ISSUE THREAD

**Issue by guenter-ms** [VolkovLabs/volkovlabs-form-panel#216]
Hi,
for extensive usage by simple customers it is very helpful to get a customizable national language support for hardcoded english words like
-true
-false
-apply (time picker)
-submit
-cancel
-save
...
Or is there already a way to do so?
Thanks guenni

**Comment by mikhail-vl** [comment]
@guenter-ms The Data Manipulation panel allows you to set custom Radio elements (instead of using default True/False) and button label options.

  The time Picker is a default Grafana component, which does not support internationalization yet.
  It's possible to rebuild Grafana to update those labels manually.

  We may add options to update Confirmation dialog if it helps.

**Comment by guenter-ms** [comment]
That helps! Thank you
