### ISSUE TITLE
Missing Scrollbar in Forms with Multiple Sections in Data Manipulation Plugin for Grafana Version 9.06

### ISSUE THREAD

**Issue by utkarshsalunkhe** [VolkovLabs/volkovlabs-form-panel#236]
Hello Community,

I hope this message finds you well. I wanted to bring to your attention an issue that I’ve encountered while using the Data Manipulation Plugins Form. I believe it’s important to share this information so that it can be addressed and improved for a better user experience.

Issue Description:
When using the Vocalabs Data Manipulation Plugins Form to fill out forms that contain multiple sections, I’ve noticed that there is no scrollbar available to navigate through the sections. This becomes problematic when the content within the sections exceeds the visible area, as it makes it difficult to access and fill out the entire form accurately. #volkalab #data_manipulation

**Comment by mikhail-vl** [comment]
@utkarshsalunkhe Thank you for reporting the issue.

  We will check and fix in the upcoming release.

**Comment by asimonok** [comment]
@utkarshsalunkhe Thank you for the reporting the issue.
I tested on Grafana `v9.0.6` and the issue is not reproduced. I was able to scroll the whole content.

<img width="1272" alt="Screenshot 2023-09-07 at 11 36 29" src="https://github.com/VolkovLabs/volkovlabs-form-panel/assets/15867703/05622631-a1bf-49d2-9166-6e1ba309f5ac">

Could you provide more details when the issue appears? JSON, screenshot, panel options, etc. It will help much in reproducing the issue.

**Comment by utkarshsalunkhe** [comment]
Thanks for asking bug is fixed now
