### ISSUE TITLE
InfluxDB / Mixed content

### ISSUE THREAD

**Issue by thomasbromkapsdata** [VolkovLabs/volkovlabs-form-panel#262]
Hi,

i'm trying to make the panel work for influxdb following [that](https://volkovlabs.io/plugins/volkovlabs-form-panel/servers/influx/)
But even if i m going to a really simple use case i can't make it work but i don't get error in Grafana either, the "submit button" run at infinit.
Inspecting elements i got some error about [mixed content](https://developer.mozilla.org/en-US/docs/Web/Security/Mixed_content?utm_source=mozilla&utm_medium=firefox-console-errors&utm_campaign=default) and Cross-Origin Request that are not allowed.

Any idea ? Sorry if i can't get a better understanding of the problem, it's beyond my basics knowledge.

**Comment by mikhail-vl** [comment]
@thomasbromkapsdata If 'submit button' run forever, then the specified URL it not able to reach and timeout, usually within 30 seconds.

  InfluxDB should alllow access without CORS restrictions to make it work following the tutorial.

  Alternatively, you can use Query and Data Source instead of REST API. We explained the details in the recent YouTube tutorial: https://www.youtube.com/watch?v=hVy9NfFiI5U. It's for Postgres, but should work for Influx in the same way.
