### ISSUE TITLE
 Request for  Dynamic Dropdown options change dynamically based on prior selections

### ISSUE THREAD

**Issue by utkarshsalunkhe** [VolkovLabs/volkovlabs-form-panel#266]
Dear Volkolabs Community,

I am actively engaged in a machine learning project that used the data manipulation plugin for form creation. One crucial functionality that we frequently require is a dynamic dropdown feature, which dynamically adjusts its options based on prior selections made within the form.

Currently, this feature is not available within the data manipulation plugin. Hence, I am reaching out to propose an enhancement to the plugin that incorporates this dynamic dropdown functionality. The ability to have dropdown options adapt dynamically based on prior selections would significantly enhance our project's efficiency. 

I kindly request the community's support and collaboration to prioritize and implement this valuable feature within the data manipulation plugin. Any contributions, suggestions, or insights from the community are highly welcomed and appreciated.

**Comment by mikhail-vl** [comment]
@asimonok Any suggestions?

**Comment by gitBitHubNet** [comment]
@utkarshsalunkhe
There is a way, it is an indirect one but it will do the job.

Lets say you have two "Select with Custom options" elements, 'dropdown1' & 'dropdown2' and you want whenever you pick something in 'dropdown1', to change the values in the 'dropdown2', accorinding to the selection the user made in 'dropdown1'.
The trick is to put your code for changing the values of 'dropdown2' inside the "Show if returned value is true" section of the 'dropdown1'.
But, because inside this section you are not allowed to use "data", "elements", "templateService", etc structures, you will have to somehow pass inside that section the data you need for changing the value. So the additional step is to create in your data manipulation form some hidden elements, which will act as storage fields, so you can retrieve the info you want from inside the "Show if returned value is true" section.

These hidden fields should be of the type "String Input" and in order to make them always hidden, put inside their "Show if returned value is true" section something that always returns false, like:

```javascript
const select = elements.find((element) => element.id === "dropdown1");
if (select) {
  return false;
}
```

You will need a hidden field named lets say "arrayData" of type "String Input" to hold all the possible values that the Dropdown2 might have. In the initial code section of the data manipulation form you will retrieve from your query the possible values for the 'dropdown2' menu and assign them to the 'arrayData' element.

```javascript
const arrayData= elements.find((element) => element.id === "arrayData");
if (arrayData) {
  arrayData.value = ...\\here you can pass the data either as a json string or simply assign an array and it will be parsed back to an array when you assign it back to a variable in the "Show if returned value is true" section of 'Dropdown2'
}
```

Now, inside the "Show if returned value is true" section of 'Dropdown2' you put something like this:

```javascript
const dropdown1= elements.find((element) => element.id === "dropdown1");
const dropdown2= elements.find((element) => element.id === "dropdown2");
const arrayData= elements.find((element) => element.id === "arrayData");

if (dropdown1) {
   switch (dropdown1.value) {//here we check which value the user selected
   case 'selectedValue1':
      dropdown2.options = ... //here we update the list of dropdown2 by use of arrayData 
      break;
   case 'selectedValue2':
     dropdown2.options = ...
     break;
}
dropdown2.value = null;//reset the menu and force the user to choose something from the new values

return true; //we return true always in order for the element to remain visible
}
```

 So every time the user makes a selection in the 'Dropdown1', the section "Show if returned value is true" of the 'dropdown2' gets activated because we are checking the 'dropdown1' value and executes the code above updating the fileds in 'dropdown2'.
