### ISSUE TITLE
How to manually update data in influxDB using this plugin?

### ISSUE THREAD

**Issue by mikhail-vl** [VolkovLabs/volkovlabs-form-panel#83]
Questions from the YouTube video comment.

To explore using direct data source update.

**Comment by thetorque** [comment]
Hi, is this functionality supported? Or is there a workaround?

**Comment by mikhail-vl** [comment]
@thetorque It should be possible to do it directly using Custom Code, but I have not looked into it yet.

  It's easy to do using custom API like the plugin was designed.

**Comment by thetorque** [comment]
It would be great if you can provide a simple example since my background is not in software / computer. I'm very new. Thank you so much.

**Comment by JasonMatuszak** [comment]
Any idea when this functionality will be implemented and pushed for utilization?

**Comment by mikhail-vl** [comment]
@JasonMatuszak Thank you for checking.

  We see a lot of requests for this functionality and will look into it with priority.

**Comment by arknoto** [comment]
Also interested in posting / writing to influxdb database using your plugin.

**Comment by mikhail-vl** [comment]
Thank you for your interest and patience. We planned on clearing the backlog for the Data Manipulation Panel in the upcoming two weeks and releasing a new version.
  This issue has already been marked as a priority in our queue.

**Comment by fercasjr** [comment]
for the ones that are still looking how to query data to InfluxDB using the API:
here is the documentation: https://docs.influxdata.com/influxdb/cloud/reference/api/

and this is an example on how to use the data manipulation plugin:
 under Update Request tab select Update Request as [ - ]  then paste this on custom code


```

const the_query=

 `
from(bucket: "bucket_example") 
	|> range(start: -1mo)
	|> filter(fn: (r) => r["_measurement"] == "measurement_example")
	|> filter(fn: (r) => r["_field"] == "field_example")
	|> window(every: 24h, period:24h ,offset:4h)
	|> last()
	|> yield(name: "last")
`


/**
 * Set URL
 */
const url = `http://localhost:8086/api/v2/query?org=org_example`;

/**
 * Fetch
 */
const resp = fetch(url, {
  method: "POST",
  headers: {
    "Content-Type": "application/vnd.flux",
    "Accept": "application / csv",
    "Authorization": "Token INFLUX_API_TOKEN",
  },
  body: the_query

})
  .catch((error) => {
    console.error(error);
  })
  .then((resp) => {
    console.log(resp);
  });

```


Of course you need to know the ip or name of the server (localhost in the example), your IfluxDB org, token etc
the query could be whatever query you already have to test. to write data to InfluxDB you can use experimental.to(), wide.to() or to() functions in the flux language or use the API. the beauty of this plugin is that you can use code to pass the variables to the query template and use the query itself to write data...  if you can execute a simple query from the plugin, then you can do pretty much anything else that the API says it's doable. 

Also you can always use Inspect on the browser to see the response of the http requests.

**Comment by fercasjr** [comment]
> for the ones that are still looking how to query data to InfluxDB using the API: here is the documentation: https://docs.influxdata.com/influxdb/cloud/reference/api/
> 
> and this is an example on how to use the data manipulation plugin: under Update Request tab select Update Request as [ - ] then paste this on custom code
> 
> ```
> 
> const the_query=
> 
>  `
> from(bucket: "bucket_example") 
> 	|> range(start: -1mo)
> 	|> filter(fn: (r) => r["_measurement"] == "measurement_example")
> 	|> filter(fn: (r) => r["_field"] == "field_example")
> 	|> window(every: 24h, period:24h ,offset:4h)
> 	|> last()
> 	|> yield(name: "last")
> `
> 
> 
> /**
>  * Set URL
>  */
> const url = `http://localhost:8086/api/v2/query?org=org_example`;
> 
> /**
>  * Fetch
>  */
> const resp = fetch(url, {
>   method: "POST",
>   headers: {
>     "Content-Type": "application/vnd.flux",
>     "Accept": "application / csv",
>     "Authorization": "Token INFLUX_API_TOKEN",
>   },
>   body: the_query
> 
> })
>   .catch((error) => {
>     console.error(error);
>   })
>   .then((resp) => {
>     console.log(resp);
>   });
> ```
> 
> Of course you need to know the ip or name of the server (localhost in the example), your IfluxDB org, token etc the query could be whatever query you already have to test. to write data to InfluxDB you can use experimental.to(), wide.to() or to() functions in the flux language or use the API. the beauty of this plugin is that you can use code to pass the variables to the query template and use the query itself to write data... if you can execute a simple query from the plugin, then you can do pretty much anything else that the API says it's doable.
> 
> Also you can always use Inspect on the browser to see the response of the http requests.

In addition here it's an example using the influx DB API

`/**
 * Set body
 */
const body = {}; //this is an empty object called body

//the following code gets each element ant if it has changed then updates the values and passes them to "body" object
options.elements.forEach((element) => {
  if (!options.update.updatedOnly) {
    body[element.id] = element.value;
    return;
  }

  /**
   * Skip not updated elements
   */
  if (element.value === initial[element.id]) {
    return;
  }

  body[element.id] = element.value;
});

/**
 * Set URL
 */

/**
 * important to declare precision for timestamp, by default is ns and in the following code we are generating a timestamp in ms
 */
const url = `http://localhost:8086/api/v2/write?org=org_example&bucket=bucket_example&precision=ms`;

/**
 * Fetch
 */
const resp = fetch(url, {
  method: "POST",
  headers: {
    "Content-Type": "text/plain; charset=utf-8",
    "Accept": "application / csv",
    "Authorization": "Token INFLUX_API_TOKEN",
  },

/**
  * This is the metric to be written in influxDB, The syntax is explained in the documentation "line-protocol"*
 */

  body: `measurement_name,tag1=${body.elment_id1} field1="${body.elment_id2}",field2="${body.elment_id3}" ${Date.now()}`

/**
* further explanation: body property is the body of the HTTP post (don't get confused with body object)*
* measurement name will be the name of the measurement to be used in InfluxDB (in this example is hard coded)* 
* tag1 is the name of the tag to be used in InfluxDB (also hard-coded)* 
* field1 and field2 will be the names of the fields to be used in InfluxDB (also hardcoded)*
* body.elment_id1 and body.elment_id2 are the values for the fields to be used in InfluxDB, I am pulling those from the grafana data manipulation plugin's  form,  that's why is inside the ${}, and body.element_id1 is getting the element_id1 from the body object (in case, is not clear enough element_id1 is the id given in the data manipulation plugin form)
and lastly Date.now() is a piece of code just for generating the timestamp (is in ms)* 
 */



})
  .catch((error) => {
    console.error(error);
  })
  .then((resp) => {
    console.log(resp);
  });
`
Hope it will help someone, I struggled a little bit too... I am not a developer but I kind of understand the basic concepts, read the documentation and bang my head against the keyboard a lot until I achieve what I was looking for.

**Comment by arknoto** [comment]
Thank you I will spin it up and try it out.  Appreciate it

**Comment by mikhail-vl** [comment]
@fercasjr Thank you for providing those. I initially considered using data sources directly instead of the InfluxDB API.

  I am going to include it in the documentation in our Servers section: https://volkovlabs.io/plugins/volkovlabs-form-panel/

**Comment by fercasjr** [comment]
> @fercasjr We updated documentation with some minor updates to your example: https://volkovlabs.io/plugins/volkovlabs-form-panel/servers/influx/
> 
> I have not used InfluxDB and would appreciate it if you could take a look and let me know if everything is correct.

seems good to me, is the template that I am using, and it works for me... of course like any other piece of code it will always depend on the environment and specifics of each user, so I think it is as general as it can be.

**Comment by mikhail-vl** [comment]
@fercasjr Thank you for confirming.
